codesuqad-team3-to-do-list/todo-max

.github/PULL_REQUEST_TEMPLATE.md
=> PR Template 추가

fe/src/styles/designSystem.ts
designSystem에 Color System 추가
[x] designSystem에 Color System 추가
designSystem에 Color System 추가했습니다. 확인하셔서 적용하시면 되겠습니다.
=> [FE] designSystem에 Color System 추가

fe/src/styles/GlobalStyles.ts
Input reset css 추가
Input reset css 추가 
Input reset css 추가했습니다. 확인하셔서 적용하시면 되겠습니다.
=> [FE] Input reset css 추가

fe/src/styles/GlobalStyles.ts
textarea reset css 추가
textarea reset css 추가
textarea reset css 추가했습니다. 확인하셔서 적용하시면 되겠습니다.
=> [FE] textarea reset css 추가

fe/src/components/Button.tsx, fe/src/components/ClosedIcon.tsx, fe/src/components/EditIcon.tsx, fe/src/components/PlusIcon.tsx, fe/src/components/main/Card.tsx
메인 페이지 UI 구현
- 버튼 컴포넌트 구현
- Card 컴포넌트 구현
- 버튼, Card 컴포넌트 구현했습니다.
=> [FE] 메인 페이지 UI 구현

README.md
- README 페이지 양식을 작성했습니다.
- README 페이지 양식을 작성
- 추후에 내용을 추가해 주세요
=> [COMMON] README 페이지 양식 작성

fe/package-lock.json, fe/package.json, fe/src/App.tsx, fe/src/components/UserInput.tsx, fe/src/components/header/Navbar.tsx, fe/src/pages/Login.tsx, fe/src/pages/Main.tsx, fe/src/pages/Sign.tsx
로그인 페이지 구현
- 라우터 기능 추가
- 로그인 페이지 구현
- 라우터 기능 및 로그인 페이지 구현했습니다
=> [FE] 로그인 페이지 구현

fe/package.json, fe/public/mockServiceWorker.js, fe/src/main.tsx, fe/src/mocks/handlers.ts, fe/src/mocks/worker.ts
MSW(Mock Service Worker)를 활용하여 Mock server를 구현했습니다.
1. MSW 라이브러리 패키지 설치
2. 서비스 워커 코드 작성
MSW로 Mock Server 구현했습니다. 확인하셔서 네트워크 요청 로직 구현하시면 됩니다.
=> [FE] MSW Mock server 구현

BE/app/build.gradle, BE/app/src/main/java/com/todo/app/common/aop/jwt/JwtAuthorizationFilter.java, BE/app/src/main/java/com/todo/app/common/config/JwtConfig.java, BE/app/src/main/java/com/todo/app/common/exception/GlobalExceptionHandler.java, BE/app/src/main/java/com/todo/app/common/exception/IllegalJwtTokenException.java, BE/app/src/main/java/com/todo/app/common/exception/IllegalPasswordException.java, BE/app/src/main/java/com/todo/app/common/exception/JwtExceptionType.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/JwtController.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/JwtRefreshTokenRequest.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/LoginRequest.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/response/JwtExceptionResponse.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/response/JwtResponse.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/response/JwtTokenType.java, BE/app/src/main/java/com/todo/app/domain/jwt/entity/Jwt.java, BE/app/src/main/java/com/todo/app/domain/jwt/entity/JwtProvider.java, BE/app/src/main/java/com/todo/app/domain/jwt/entity/Member.java, BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepository.java, BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepositoryImpl.java, BE/app/src/main/java/com/todo/app/domain/jwt/service/JwtService.java
- Jwt를 활용한 로그인 기능 개발
- [v] 로그인 API 추가 - 로그인 시 Access Token, Refresh Token 발급
- [v] 일반 API 요청 시 Filter에서 Access Token 검증 후 Token의 Claims값 Controller로 넘겨주기
- [v] Access Token 만료 시 Refresh Token으로 재발급 하는 API 추가
- [v] Refresh Token 만료 시 예외 반환하기
- 토큰이 만료된 경우를 FE 쪽에 전달하기 위해 새로운 예외 객체를 만들게 되었습니다.
- `com.todo.app.domain.jwt.controller.response.JwtExceptionResponse.java`
- 다른 예외들도 exceptionType(CUSTOM_EXCEPTION)을 추가하여 같은 형식으로 묶었으면 합니다.
- GlobalExceptionHandler에서 비슷한 로직들을 공통으로 처리할 수 있을 것 같습니다.
```json
{
"statusCode": 401,
"message":{
"exceptionType": "EXPIRED_JWT_EXCEPTION",
"message": "기한이 만료되었습니다."
}
}
```
- Filter Component로 등록 하기
=> [BE] JWT 로그인 기능 추가 (미완성)

fe/src/components/Button.tsx, fe/src/components/main/Card.tsx, fe/src/components/main/Column.tsx, fe/src/pages/Main.tsx, fe/src/types/commons.d.ts
카드 이동 기능 구현입니다
-  카드 이동 드래그 UI
=> [FE] 카드 이동 기능 구현

BE/app/src/main/java/com/todo/app/common/config/WebConfig.java, BE/app/src/main/java/com/todo/app/domain/column/controller/response/ColumnResponse.java, BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
=> [BE] CORS 설정 및 기타 코드 수정

BE/app/src/main/java/com/todo/app/common/exception/GlobalExceptionHandler.java, BE/app/src/main/java/com/todo/app/common/exception/MemberDuplicationException.java, BE/app/src/main/java/com/todo/app/common/filter/JwtAuthorizationFilter.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/JwtController.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/request/SignInRequest.java, BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepository.java, BE/app/src/main/java/com/todo/app/domain/jwt/repository/JwtRepositoryImpl.java, BE/app/src/main/java/com/todo/app/domain/jwt/service/JwtService.java
- 회원 가입 기능을 구현했습니다.
- URI: `POST` `/api/signin`
- email, password를 받아서 회원 가입 합니다.
- email로 이미 가입한 email인지 검증한 뒤 회원 가입 합니다.
- email이 중복일 경우 회원 가입에 실패하며 400 BAD REQUEST를 반환합니다.
- 회원 가입 성공일 경우 201 Created를 반환합니다.
- 아직 JWT 인증 쪽 리팩토링이 되지 않아 URI, 패키지 구조, class 명 등 수정해야 할 부분이 있는지 확인해 봐야 할 듯.
=> [BE] 회원 가입 기능 구현

BE/app/src/main/java/com/todo/app/common/ApiResponse.java, BE/app/src/main/java/com/todo/app/common/exception/GlobalExceptionHandler.java, BE/app/src/main/java/com/todo/app/common/filter/JwtAuthorizationFilter.java
- 예외 발생시 Http Response Message에도 상태코드 적용
- ApiResponse의 필드 message를 data로 변경
=> [BE] Bug hot fix

BE/app/src/main/java/com/todo/app/domain/column/controller/CardController.java, BE/app/src/main/java/com/todo/app/domain/column/controller/request/CardMoveRequest.java, BE/app/src/main/java/com/todo/app/domain/history/repository/HistoryRepositoryImpl.java
- Code With Me 사용법 미숙으로 일부 commit이 올라가지 않아 다시 올립니다.
- 카드 이동시 컬럼이 이동했는지 체크하는 로직도 수정되었습니다.
=> [BE] 누락된 코드 추가

BE/app/src/main/java/com/todo/app/common/exception/CustomBusinessException.java, BE/app/src/main/java/com/todo/app/common/exception/GlobalExceptionHandler.java, BE/app/src/main/java/com/todo/app/common/exception/IllegalJwtTokenException.java, BE/app/src/main/java/com/todo/app/common/exception/IllegalPasswordException.java, BE/app/src/main/java/com/todo/app/common/exception/MemberDuplicationException.java, BE/app/src/main/java/com/todo/app/common/exception/ResourceNotFoundException.java, BE/app/src/main/java/com/todo/app/common/filter/JwtAuthorizationFilter.java, BE/app/src/main/java/com/todo/app/domain/jwt/controller/JwtController.java, BE/app/src/main/java/com/todo/app/domain/jwt/service/JwtService.java
=> [BE] JWT 로그인 로직 부분 리팩토링

BE/app/src/main/java/com/todo/app/domain/column/controller/CardController.java, BE/app/src/main/java/com/todo/app/domain/column/domain/Card.java, BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepository.java, BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java, BE/app/src/main/java/com/todo/app/domain/column/service/CardService.java, BE/app/src/main/java/com/todo/app/domain/column/service/CardServiceImpl.java
=> [BE] 카드 수정 시 수정된 내용을 반환하도록 변경

BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepository.java, BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java, BE/app/src/main/java/com/todo/app/domain/column/service/CardServiceImpl.java
카드 역순 정렬하여 반환하게 수정
* ``` CardServiceImpl```의 create()메서드 수정
* ```CardRepositoryImpl```의 findFirstCardWeightValue() 수정
=> [BE] 카드 역순 정렬하여 반환하게 수정

fe/src/components/main/Card.tsx, fe/src/components/main/CardContent.tsx, fe/src/components/main/Column.tsx, fe/src/components/main/ColumnTitle.tsx, fe/src/main.tsx, fe/src/pages/Main.tsx, fe/src/types/commons.d.ts, fe/src/useFetch.tsx
카드 추가, 삭제, 편집 기능 구현입니다.
- 카드 추가 기능
- 카드 삭제 기능
- 카드 편집 기능
=> [FE] 카드 추가, 삭제, 편집 기능 구현

BE/app/src/main/java/com/todo/app/domain/column/controller/ColumnController.java, BE/app/src/main/java/com/todo/app/domain/column/service/CardServiceImpl.java, BE/app/src/main/java/com/todo/app/domain/column/service/ColumnServiceImpl.java
=> [BE] 로그인 로직 적용

BE/app/deploy.sh
=> [BE] 배포 스크립트 작성

BE/app/src/main/java/com/todo/app/domain/column/domain/Card.java, BE/app/src/main/java/com/todo/app/domain/column/repository/CardRepositoryImpl.java
- 카드 생성시 500에러 반환하는 버그 수정
- Card 객체 생성시 author가 null인 경우 기본값을 주도록 변경하여 해결
=> [BE] 카드 생성시 500에러 반환하는 버그 수정

README.md
=> 📝docs: Update README.md
